### ISSUE TITLE
OSX Xcode 7.0.1, Node 4.2.1 - not working

### ISSUE THREAD

**Issue by srl295** [strongloop-forks/strong-fork-syslog#8]
```
> strong-fork-syslog@1.2.3 install /Users/srl/src/strong-fork-syslog
> node-gyp rebuild

  CXX(target) Release/obj.target/syslog/syslog.o
In file included from ../syslog.cc:2:
../compat-inl.h:288:37: error: no member named 'StartCpuProfiling' in 'v8::CpuProfiler'; did you mean 'StartProfiling'?
  return isolate->GetCpuProfiler()->StartCpuProfiling(title, record_samples);
                                    ^~~~~~~~~~~~~~~~~
                                    StartProfiling
/Users/srl/.node-gyp/4.2.1/include/node/v8-profiler.h:201:8: note: 'StartProfiling' declared here
  void StartProfiling(Local<String> title, bool record_samples = false);
       ^
In file included from ../syslog.cc:2:
../compat-inl.h:294:37: error: no member named 'StopCpuProfiling' in 'v8::CpuProfiler'; did you mean 'StopProfiling'?
  return isolate->GetCpuProfiler()->StopCpuProfiling(title);
                                    ^~~~~~~~~~~~~~~~
                                    StopProfiling
/Users/srl/.node-gyp/4.2.1/include/node/v8-profiler.h:207:15: note: 'StopProfiling' declared here
  CpuProfile* StopProfiling(Local<String> title);
              ^
In file included from ../syslog.cc:2:
../compat-inl.h:310:55: error: no viable conversion from 'v8::Local<v8::String>' to 'v8::ActivityControl *'
  return isolate->GetHeapProfiler()->TakeHeapSnapshot(title);
                                                      ^~~~~
/Users/srl/.node-gyp/4.2.1/include/node/v8-profiler.h:487:24: note: passing argument to parameter 'control' here
      ActivityControl* control = __null,
                       ^
3 errors generated.
make: *** [Release/obj.target/syslog/syslog.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/srl/src/strong-fork-syslog
gyp ERR! node -v v4.2.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! strong-fork-syslog@1.2.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the strong-fork-syslog@1.2.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the strong-fork-syslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls strong-fork-syslog
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/srl/src/strong-fork-syslog/npm-debug.log
```

**Comment by rmg** [comment]
This module has been deprecated and replaced by https://github.com/strongloop/modern-syslog - we have no intention of fixing it.
